### ISSUE TITLE
Templates assume dev server port is 3000

### ISSUE THREAD

**Issue by Dan-Shields** [nodecg/vite-plugin-nodecg#4]
Easily fixed by reading port from the resolved config

**Comment by zoton2** [comment]
A few notes:

- Since Vite v3 the default port is `5173`, so that needs updating too.
- If Vite has to choose a different port, it seems like that port isn't decided until the HTTP server is `listening`, but I'm not sure if that has a special hook or if you just have to do something like below, which then you could maybe run `generateHTMLFiles()` in there instead? Although IIRC this config will still have the wrong `server.origin` address and you need to refer to `server.port` instead.
```
configureServer(server) {
    server.httpServer.once('listening', () => {
        // server.config will have the correct config, kind of
    }
}
```
- I see that the `config` hook chooses the protocol and socket address, then stores them in a *different* set of variables, which are then used for development. Is that done for any specific reason over just using the normal configuration? (Although in the above case of changing ports, it still wouldn't work and would need regenerating).

**Comment by Dan-Shields** [comment]
Thanks for your notes on this @zoton2, should be fixed!
